[package]
name = "sha3"
version = "0.1.1"
description = "Motoko Sha3/Keccak library"
repository = "https://github.com/hanbu97/motoko-sha3"
keywords = [ "sha3", "keccak", "hash", "eth" ]

[dependencies]
base = "0.8.2"
iterext = "https://github.com/timohanke/motoko-iterext#v2.0.0"